export const FRONT_AIM_MIN_TRACKING_CONFIDENCE = 0.5;

export const FRONT_AIM_LOST_FRAME_GRACE_FRAMES = 3;

export const DEFAULT_FRONT_AIM_CENTER_X = 0.5;
export const DEFAULT_FRONT_AIM_CENTER_Y = 0.5;
export const DEFAULT_FRONT_AIM_CORNER_LEFT_X = 0;
export const DEFAULT_FRONT_AIM_CORNER_RIGHT_X = 1;
export const DEFAULT_FRONT_AIM_CORNER_TOP_Y = 0;
export const DEFAULT_FRONT_AIM_CORNER_BOTTOM_Y = 1;
export const MIN_FRONT_AIM_CORNER_SPAN = 0.05;
