export const SIDE_TRIGGER_PULL_ENTER_THRESHOLD = 0.72;
export const SIDE_TRIGGER_PULL_EXIT_THRESHOLD = 0.55;
export const SIDE_TRIGGER_RELEASE_ENTER_THRESHOLD = 0.7;
export const SIDE_TRIGGER_RELEASE_EXIT_THRESHOLD = 0.5;
export const SIDE_TRIGGER_MIN_PULL_DWELL_FRAMES = 2;
export const SIDE_TRIGGER_MIN_RELEASE_DWELL_FRAMES = 2;
export const SIDE_TRIGGER_STABLE_POSE_REQUIRED_FRAMES = 1;
export const SIDE_TRIGGER_LOST_HAND_GRACE_FRAMES = 3;
export const SIDE_TRIGGER_SHOT_COOLDOWN_FRAMES = 5;
export const SIDE_TRIGGER_MIN_CONFIDENCE_FOR_COMMIT = 0.55;
export const DEFAULT_SIDE_TRIGGER_OPEN_POSE_DISTANCE = 1.2;
export const DEFAULT_SIDE_TRIGGER_PULLED_POSE_DISTANCE = 0;
export const INITIAL_SIDE_TRIGGER_OPEN_POSE_DISTANCE = 1.2;
export const INITIAL_SIDE_TRIGGER_PULLED_POSE_DISTANCE = 0.2;
export const MIN_SIDE_TRIGGER_CALIBRATION_DISTANCE_SPAN = 0.05;

// r9 cycle-driven calibration constants
export const CYCLE_BASELINE_WINDOW_MS = 300;
export const CYCLE_BASELINE_MIN_SAMPLES = 10;
export const CYCLE_DROP_THRESHOLD = 0.05;
export const CYCLE_HOLD_DURATION_MS = 50;
export const CYCLE_RECOVERY_RATIO = 0.8;
export const CYCLE_POST_OPEN_WINDOW_MS = 200;
export const CYCLE_STABLE_OPEN_INTERVAL_MS = 500;

export const CAL_ALPHA_PULL = 0.1;
export const CAL_ALPHA_OPEN_CYCLE = 0.1;
export const CAL_ALPHA_OPEN_ASSIST = 0.02;
export const CAL_CYCLE_MIN_INTERVAL_MS = 200;
export const CAL_CYCLE_MAX_DURATION_MS = 1000;
export const CAL_OPEN_MEDIAN_MAX_DEVIATION = 0.3;
export const CAL_LAST_CYCLE_MAX_DEVIATION = 0.5;

export const CTRL_HAND_LOSS_THRESHOLD_MS = 1500;
export const CTRL_GEOMETRY_JUMP_RATIO = 0.25;
export const CTRL_GEOMETRY_EMA_ALPHA = 0.1;
